faraday update 0.12.0 => 1.9.3
maedadev/bizside-ruby pull request #28
Opened 2022-06-28 08:47 UTC by macera

* gem faraday のアップデート
  * 1系の最新バージョンv1.9.3にする

* すでにmainに他の修正があったのでそれらは別バージョンにわけたいので別コミットにしました。

2022-06-28 08:57 UTC, xketanaka requested changes

2022-06-28 08:57 UTC, xketanaka commented on bizside.gemspec
> +  s.add_runtime_dependency 'faraday', '~> 1.9.3'
`>= 0.12`, `< 2.0` ではまずいですか？

2022-06-28 09:48 UTC, xketanaka commented on bizside.gemspec
> +  s.add_runtime_dependency 'faraday', '~> 1.9.3'
対応ありがとうございました。

2022-06-28 09:49 UTC, xketanaka approved these changes

2022-06-29 09:39 UTC, merged

2022-06-30 00:26 UTC, m-shimojo commented on HISTORY.md
> +  * faraday version up 0.12 => 1.9.3(#62048)
バージョンの記述について修正が必要だと思います。